### ISSUE TITLE
Deploy pkgdown site

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/recocam#4]
Pkgdown does a lovely job of making an easy to use website for packages. How about we deploy one?

**Comment by dvanic** [comment]
Might be helpful, although depends how much time you have left on this project

**Comment by hlydecker** [comment]
Yeah I have no idea how much time it would take or what it would entail. It took me ~5 minutes to deploy a shiny app, but idk if there is a way for me to quickly deploy this. Maybe Sergio's cross skilling will help.

**Comment by dvanic** [comment]
If your documentation is already in roxygen then it's straightforward, and the recommended way of hosting is github pages from the docs folder:
> The easiest way to publish your website is to use GitHub docs/ directory support. If you want to build and publish your package automatically with GitHub actions, try usethis::use_github_action("pkgdown").

https://pkgdown.r-lib.org/articles/pkgdown.html

**Comment by hlydecker** [comment]
Wow pkgdown is the best. That was absurdly easy and quick to do!
